export enum UserRole {
    SUPER_ADMIN = 'SUPER_ADMIN',
    PROJECT_MANAGER = 'PROJECT_MANAGER',
    TEAM_MEMBER_INHOUSE = 'TEAM_MEMBER_INHOUSE',
    OUTSOURCED_TEAM = 'OUTSOURCED_TEAM',
    FINANCE_TEAM = 'FINANCE_TEAM',
}
